using System.Reflection;
using Shouldly;
using WinLogRotate.Contracts;
using WinLogRotate.Core.Configuration;
using Xunit;

namespace WinLogRotate.Core.Tests;

/// <summary>
/// That a <c>[job]</c> key is noticed - whether it is misspelled, or bound and then dropped.
/// </summary>
public sealed class JobKeyTests
{
    private static (JobConfig? Job, DiagnosticBag Bag) Bind(string body)
    {
        var bag = new DiagnosticBag();
        var file = TomlFile.Parse(
            "schema = 1\n[job]\nname = \"app\"\npaths = [\"C:/logs/*.log\"]\n" + body, "app.toml");

        return (ConfigBinder.BindJob(file, bag), bag);
    }

    private static ConfigDiagnostic Only(DiagnosticBag bag, string code) =>
        bag.Items.ShouldHaveSingleItem(
            $"expected exactly one {code}, got: {string.Join("; ", bag.Items.Select(i => i.Message))}");

    // ---- the misspelling ---------------------------------------------------------------------

    /// <summary>
    /// A mistyped hook key is reported instead of discarded.
    /// </summary>
    /// <remarks>
    /// <c>[job]</c> reported no unknown keys at all until this milestone, so <c>postrotae</c> bound
    /// cleanly, validated cleanly, and did nothing forever. <c>[notify]</c> has warned about its
    /// own since it existed, for the reason its binder gives out loud: a mistyped setting silently
    /// disables the thing it was meant to configure, and the discovery happens during the incident
    /// it was supposed to prevent.
    /// </remarks>
    [Fact]
    public void AMisspelledHookKeyIsReported()
    {
        var (job, bag) = Bind("postrotae = [\"service:paramchange:W3SVC\"]\n");

        job.ShouldNotBeNull();
        var reported = Only(bag, "unknown key");
        reported.Severity.ShouldBe(Severity.Warning);
        reported.Message.ShouldContain("postrotae");
        reported.Remedy.ShouldNotBeNull().ShouldContain("postrotate", Case.Sensitive);
    }

    /// <summary>
    /// The three logrotate script kinds an import used to write out as live keys.
    /// </summary>
    /// <remarks>
    /// The importer no longer emits them, but a configuration generated by an older build is still
    /// sitting in somebody's conf.d - looking exactly like a working directive, next to a
    /// postrotate that does work.
    /// </remarks>
    [Theory]
    [InlineData("firstaction")]
    [InlineData("lastaction")]
    [InlineData("preremove")]
    public void TheScriptKindsWeDoNotSupportAreReported(string key)
    {
        var (_, bag) = Bind($"{key} = [\"service:paramchange:W3SVC\"]\n");

        Only(bag, "unknown key").Message.ShouldContain(key);
    }

    /// <summary>
    /// A suggestion is offered only when there is exactly one candidate.
    /// </summary>
    /// <remarks>
    /// <c>firstaction</c> is a different directive, not a misspelling of <c>postrotate</c>, and
    /// proposing one would send somebody off to write a hook with the wrong semantics.
    /// </remarks>
    [Fact]
    public void ADifferentDirectiveIsNotProposedAsASpellingFix()
    {
        var (_, bag) = Bind("firstaction = [\"x\"]\n");

        Only(bag, "unknown key").Remedy.ShouldNotBeNull().ShouldNotContain("Did you mean");
    }

    [Fact]
    public void EveryRealJobKeyIsAccepted()
    {
        var (_, bag) = Bind("""
            kind = "rotate"
            enabled = true
            daily = true
            rotate = 7
            compress = true
            compresstype = "zip"
            delaycompress = true
            dateext = true
            dateformat = "-yyyyMMdd"
            missingok = true
            notify = false
            notifempty = false
            olddir = "C:/archive"
            createolddir = true
            lockstrategy = "rename"
            livefiles = 1
            maxfiles = 500
            retrycount = 3
            retryinterval = 200
            maxage = 30
            minage = 1
            minsize = "1M"
            maxsize = "10M"
            start = 1
            weekday = 0
            monthday = 0
            allowdangerous = []
            prerotate = ["service:paramchange:W3SVC"]
            postrotate = ["service:paramchange:W3SVC"]
            hook_timeout = "30s"
            """);

        bag.Items.ShouldBeEmpty(string.Join("; ", bag.Items.Select(i => i.Message)));
    }

    // ---- the copy block --------------------------------------------------------------------

    /// <summary>
    /// Every setting <c>BindSettings</c> reads survives <c>BindJob</c>'s hand-written copy.
    /// </summary>
    /// <remarks>
    /// <c>BindJob</c> copies twenty-nine properties one at a time from the <c>JobSettings</c> it
    /// just bound into the <c>JobConfig</c> it returns. A property added to one and forgotten in
    /// the other binds correctly, merges correctly, and is then silently discarded - with no
    /// compiler error, because both types have the property and neither is required on
    /// <c>JobSettings</c>. That is the same shape as every defect the last two milestones fixed,
    /// so it gets a test rather than care.
    /// </remarks>
    [Fact]
    public void AHookSettingBoundButNotCopiedIsCaught()
    {
        // Every JobSettings property, with a TOML key and a value that is not the default. A new
        // property with no entry here fails the test below, which is the point: the author has to
        // come to this list, and getting here means noticing BindJob's copy block exists.
        var samples = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [nameof(JobSettings.Schedule)] = "schedule = \"weekly\"",
            [nameof(JobSettings.Weekday)] = "weekday = 3",
            [nameof(JobSettings.MonthDay)] = "monthday = 5",
            [nameof(JobSettings.Rotate)] = "rotate = 11",
            [nameof(JobSettings.Start)] = "start = 2",
            [nameof(JobSettings.MaxAge)] = "maxage = 45",
            [nameof(JobSettings.MinAge)] = "minage = 2",
            [nameof(JobSettings.MinSize)] = "minsize = \"3M\"",
            [nameof(JobSettings.MaxSize)] = "maxsize = \"9M\"",
            [nameof(JobSettings.SizeThreshold)] = "size = \"7M\"",
            [nameof(JobSettings.Compress)] = "compress = false",
            [nameof(JobSettings.CompressType)] = "compresstype = \"gzip\"",
            [nameof(JobSettings.DelayCompress)] = "delaycompress = true",
            [nameof(JobSettings.DateExt)] = "dateext = true",
            [nameof(JobSettings.DateFormat)] = "dateformat = \"-yyyy-MM-dd\"",
            [nameof(JobSettings.MissingOk)] = "missingok = true",
            [nameof(JobSettings.Notify)] = "notify = false",
            [nameof(JobSettings.NotIfEmpty)] = "notifempty = false",
            [nameof(JobSettings.OldDir)] = "olddir = \"C:/archive\"",
            [nameof(JobSettings.CreateOldDir)] = "createolddir = true",
            [nameof(JobSettings.LockStrategy)] = "lockstrategy = \"copytruncate\"",
            [nameof(JobSettings.LiveFiles)] = "livefiles = 4",
            [nameof(JobSettings.MaxFiles)] = "maxfiles = 77",
            [nameof(JobSettings.RetryCount)] = "retrycount = 9",
            [nameof(JobSettings.RetryIntervalMs)] = "retryinterval = 250",
            [nameof(JobSettings.PreRotate)] = "prerotate = [\"service:paramchange:a\"]",
            [nameof(JobSettings.PostRotate)] = "postrotate = [\"service:paramchange:b\"]",
            [nameof(JobSettings.HookTimeout)] = "hook_timeout = \"42s\"",
        };

        var properties = typeof(JobSettings)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .ToArray();

        properties.Select(p => p.Name).ShouldBeSubsetOf(
            samples.Keys,
            "a JobSettings property with no sample here would not be covered - add one, and check "
            + "ConfigBinder.BindJob copies it and ConfigBinder.JobKeys lists its key");

        foreach (var property in properties)
        {
            var (job, bag) = Bind(samples[property.Name] + "\n");

            job.ShouldNotBeNull($"{property.Name}: {string.Join("; ", bag.Items.Select(i => i.Message))}");
            bag.Items.ShouldBeEmpty($"{property.Name} produced a diagnostic");

            property.GetValue(job).ShouldNotBeNull(
                $"{property.Name} was bound and then dropped by BindJob's copy block");
        }
    }

    /// <summary>Every key in the sample list is a key the unknown-key rule knows about.</summary>
    [Fact]
    public void TheKnownKeyListCoversWhatTheBinderReads()
    {
        // Bind a file setting every key at once; anything the binder reads but JobKeys omits shows
        // up here as a warning about a key that demonstrably works.
        var (_, bag) = Bind("hourly = false\nweekly = false\nmonthly = false\nyearly = false\n");

        bag.Items.ShouldBeEmpty(string.Join("; ", bag.Items.Select(i => i.Message)));
    }
}
